-- 코드를 입력하세요
-- 조건 : 2022년 10월 작성된 게시글 (댓글까지인가 ... ? )
-- 정렬: 댓글 작성일(USED_GOODS_REPLY - CREATED_DATE) 기준 오름차순, 댓글 작성일 같다면 제목(USED_GOODS_BOARD - TITLE) 기준 오름차순

SELECT B.TITLE,	B.BOARD_ID,	R.REPLY_ID,	R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_REPLY R JOIN USED_GOODS_BOARD B ON R.BOARD_ID = B.BOARD_ID
where B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
order bY R.CREATED_DATE, B.TITLE;